name: Journalism
version: '${version}'

main: net.shinyshoe.journalism.Journalism
api-version: '26.2'
load: POSTWORLD

permissions:
  journalism.reload:
    description: Use /journal reload
    default: op
  journalism.manage:
    description: Use /journal section, /journal category and /journal entry
    default: op
